FROM openjdk:17-jdk-slim

COPY src /app/src

WORKDIR /app

COPY pom.xml /app

RUN mvn clean install -DskipTests

RUN ls -lh /app/target


#
# Package stage
#
FROM openjdk:17-jdk-slim

WORKDIR /app

COPY --from=build /app/target/VestraPay-0.0.1-SNAPSHOT.jar app.jar

EXPOSE 5050

ENTRYPOINT ["java","-jar","app.jar"]
