CREATE TABLE IF NOT EXISTS business (
   id SERIAL PRIMARY KEY,
   uuid VARCHAR(100) NOT NULL UNIQUE ,
   merchant_id VARCHAR(100) NOT NULL UNIQUE,
   business_name VARCHAR(100) NOT NULL ,
   business_address VARCHAR(255) NOT NULL ,
   business_phone_number VARCHAR(20) NOT NULL ,
   business_email VARCHAR(20) NOT NULL UNIQUE,
   business_support_phone_number VARCHAR(20) NOT NULL UNIQUE,
   business_support_email_address VARCHAR(50) NOT NULL UNIQUE,
   country VARCHAR(50) NOT NULL,
   chargeback_email VARCHAR(100) NOT NULL,
   customer_pay_txn_fee boolean NOT NULL,
   notification_email boolean NOT NULL,
   customer_email boolean NOT NULL,
   credit_notification boolean NOT NULL,
   notify_business_email boolean NOT NULL,
   notify_dashboard_users boolean NOT NULL,
   send_to_specific_users text NOT NULL ,
   two_factor_login boolean NOT NULL,
   two_factor_for_transfer boolean NOT NULL,
   transfer_via_api boolean NOT NULL,
   transfer_via_dashboard boolean NOT NULL,
   disable_all_transfers boolean NOT NULL,
   payment_methods varchar(255) NOT NULL,
   date_created TIMESTAMP WITHOUT TIME ZONE,
   date_updated TIMESTAMP WITHOUT TIME ZONE
);