CREATE TABLE IF NOT EXISTS payment_methods (
       id SERIAL PRIMARY KEY,
       uuid VARCHAR(100) NOT NULL UNIQUE ,
       name VARCHAR(100) NOT NULL UNIQUE ,
       created_at TIMESTAMP WITHOUT TIME ZONE,
       updated_at TIMESTAMP WITHOUT TIME ZONE
);